// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for better security
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hmrkhhibftmubrpejipl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLIC_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmtoaGliZnRtdWJycGVqaXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjA1NDcsImV4cCI6MjA2MDEzNjU0N30.P-tjM9oTm8Jb3QJ__VoaR79HH8tqTBWcaG83AEaT1EY";

// Create a single supabase client for interacting with your database
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    storageKey: 'semnotes-auth',
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'SemNotes Web App'
    },
  }
});

// console.log("[SUPABASE] Client initialized with persistSession=true and autoRefreshToken=true");

// Type definitions to prevent circular references
export type SubjectType = {
  id: string;
  name: string;
  branch: string;
  academic_year: number;
  semester: number;
  is_common: boolean;
  created_at?: string;
};

export type StudentType = {
  id: string;
  email: string | null;
  full_name: string | null;
  branch: string | null;
  academic_year: number | null;
  semester: number | null;
  is_admin?: boolean;
  created_at?: string;
};

// Type augmentation for notes - temporary solution until types.ts is regenerated
export type NoteWithApproval = Database['public']['Tables']['notes']['Row'] & {
  is_approved: boolean;
};

// Break circular references by separating subject and student types
export type NoteSubject = {
  name: string;
  branch: string;
  academic_year: number;
  semester: number;
};

export type NoteStudent = {
  email: string | null;
  full_name: string | null;
  branch: string | null;
  academic_year: number | null;
  semester: number | null;
};

export type NoteWithSubject = NoteWithApproval & {
  subject?: NoteSubject;
  student?: NoteStudent;
};

// Storage initialization has been moved to storage-init.ts to avoid RLS policy issues
// DO NOT add storage initialization code here as this file is auto-generated
